# Generated by Django 4.1.5 on 2023-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('it', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
