# Generated by Django 4.1.5 on 2023-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='cokolwiek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
