# Generated by Django 4.1.5 on 2023-01-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_bookcopy_cokolwiek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='cokolwiek',
        ),
    ]
