# Generated by Django 4.1.5 on 2023-01-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher_name',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='copy_id',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='librarian_id',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='branch_id',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookCopy',
        ),
        migrations.DeleteModel(
            name='BookIssue',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='LibraryUser',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
