# Generated by Django 4.1.5 on 2023-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_remove_bookcopy_cokolwiek'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LibraryUser',
        ),
        migrations.AlterModelTable(
            name='libraryuser',
            table='LibraryUser',
        ),
    ]
