# Generated by Django 4.1.5 on 2023-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0004_rename_user_libraryuser_alter_libraryuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
