# Generated by Django 4.1.5 on 2023-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0005_rename_card_number_bookissue_library_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
