# Generated by Django 4.1.5 on 2023-02-01 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0006_bookissue_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator]),
        ),
    ]
